typography_spectrum: 0.5
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73207
analytics:
  google: null
  facebook: null
  twitter: null
name: '#softfab'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about
    id: a0a94be6-2ab6-4a0e-887a-1b692aa76592
    type: content
favicon: null
purpose: []
